# Generated by Django 2.1.7 on 2019-03-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_time', models.TimeField(default='16:00:00')),
                ('location', models.CharField(max_length=30)),
                ('ss_number', models.PositiveIntegerField(default=1)),
                ('bb_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
