# Generated by Django 2.1.7 on 2019-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('ss_number', models.PositiveIntegerField(default=1)),
                ('bb_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
